CIPlatformWeb/Controllers/PolicyController.cs
using CIPlatformWeb.Entities.DataModels;
using CIPlatformWeb.Entities.ViewModels;
using CIPlatformWeb.Repositories.GenericRepository.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Net.Mail;
using System.Net;

namespace CIPlatformWeb.Controllers
{
    public class PolicyController : CommonController
    {
        private readonly IUnitOfWork _uow;
        public PolicyController(IUnitOfWork uow) : base(uow)
        {
            _uow = uow;
        }

        public IActionResult PolicyAndCookies()
        {
            User? user = GetThisUser();
            if (user != null)
            {
                PolicyViewModel obj = new();
                obj.UserDetail = _uow.User.GetFirstOrDefault(u => u.UserId == user.UserId);
                return View(obj);
            }
            return View();
        }

        public IActionResult ContactUsMail(string mailSubject, string mailBody)
        {
            User user = GetThisUser();
            if (user != null)
            {
                ContactU contactDetail = new()
                {
                    UserId = user.UserId,
                    Subject = mailSubject,
                    Message = mailBody,
                };
                _uow.ContactUs.Add(contactDetail);
                _uow.Save();

                string body = $"HI ,<br /><br />{mailBody}<br /><br /> From {user.FirstName + " " + user.LastName}";
                MailMessage msg = new(user.Email, "jaypalsinhrana12345@gmail.com")
                {
                    Subject = mailSubject,
                    Body = body,
                    IsBodyHtml = true
                };

                try
                {
                    SendMail(msg);
                    return Json(1);
                }
                catch
                {
                    TempData["error"] = "Opps! Something went wrong, try again later.";
                }
            }
            return Json(0);
        }
    }
}

CIPlatformWeb/Controllers/UserController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using CIPlatformWeb.Repositories.GenericRepository.Interface;
using CIPlatformWeb.Entities.DataModels;
using System.Security.Claims;
using CIPlatformWeb.Entities.ViewModels;
using System.Collections.Generic;
using NUnit.Framework;
using System.Linq;
using Microsoft.AspNetCore.Authorization;

namespace CIPlatformWeb.Controllers
{
    public class UserController : CommonController
    {
        private readonly IUnitOfWork _uow;
        public UserController(IUnitOfWork uow) : base(uow)
        {
            _uow = uow;
        }

        //user profile page
        [Authorize]
        [HttpGet]
        public IActionResult Profile()
        {
            User user = GetThisUser();
            IEnumerable<Skill> skillList = _uow.Skill.GetAccToFilter(skill => skill.DeletedAt == null);
            IEnumerable<Country> countryList = _uow.Country.GetAll();
            IEnumerable<UserSkill> userSkillList = _uow.UserSkill.GetAccToFilter(userSkill => userSkill.UserId == user.UserId);
            UserViewModel obj = new()
            {
                UserDetail = user,
                SkillList = skillList,
                UserSkillList = userSkillList,
                CountryList = countryList,
                FirstName = user.FirstName,
                LastName = user.LastName,
                Title = user.Title,
                ProfileText = user.ProfileText,
                CountryId = user.CountryId,
                CityId = user.CityId,
                WhyIVolunteer = user.WhyIVolunteer,
                EmployeeId = user.EmployeeId,
                Department = user.Department,
                LinkedInUrl = user.LinkedInUrl,
            };
            return View(obj);
        }

        //update profile pic
        [HttpPost]
        public IActionResult UpdateProfilePic(IFormFile profile_Pic)
        {
            User? user = GetThisUser();

            if (user != null && profile_Pic != null)
            {
                string imgExt = Path.GetExtension(profile_Pic.FileName);
                if (imgExt == ".jpg" || imgExt == ".png" || imgExt == ".jpeg")
                {
                    if (user.Avatar != null)
                    {
                        string fileName = Path.Combine(user.UserId + profile_Pic.FileName);
                        string imagePathForDb = Path.Combine("/ProfilePics/" + fileName);
                        string finalPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/" + imagePathForDb);
                        if (!imagePathForDb.Equals(user.Avatar))
                        {
                            string alrExists = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/" + user.Avatar);
                            if (System.IO.File.Exists(alrExists))
                            {
                                System.IO.File.Delete(alrExists);
                            }

                            using (FileStream stream = new(finalPath, FileMode.Create))
                            {
                                profile_Pic.CopyTo(stream);
                            }
                            user.Avatar = imagePathForDb;
                            user.UpdatedAt = DateTime.Now;
                            _uow.User.Update(user);
                        }
                    }
                    else
                    {
                        string fileName = Path.Combine(user.UserId + profile_Pic.FileName);
                        string imagePathForDb = Path.Combine("/ProfilePics/" + fileName);
                        string finalPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/" + imagePathForDb);
                        using (FileStream stream = new(finalPath, FileMode.Create))
                        {
                            profile_Pic.CopyTo(stream);
                        }
                        user.Avatar = imagePathForDb;
                        user.UpdatedAt = DateTime.Now;
                        _uow.User.Update(user);
                    }
                }
            }
            _uow.Save();
            return RedirectToAction("Profile");
        }

        //change password 
        [HttpPost]
        public IActionResult ChangePassword(UserViewModel obj)
        {
            User? user = GetThisUser();
            if (user != null && obj.OldPassword != null && obj.NewPassword != null)
            {
                if (BCrypt.Net.BCrypt.Verify(obj.OldPassword, user.Password))
                {
                    string newPass = BCrypt.Net.BCrypt.HashPassword(obj.NewPassword);

                    user.Password = newPass;
                    user.UpdatedAt = DateTime.Now;
                    _uow.User.Update(user);
                    _uow.Save();

                    return Json(1);
                }
            }

            return Json(0);
        }

        //get city according to selected country
        public JsonResult CascadeCity(long countryId)
        {
            User user = GetThisUser();
            var cityId = user.CityId;
            IEnumerable<City> cityList = _uow.City.GetAccToFilter(city => city.CountryId == countryId);
            return new JsonResult(new { CityId = cityId, Cities = cityList });
        }

        //update user details
        [HttpPost]
        public IActionResult UpdateUser(UserViewModel obj, List<long> finalSkillList)
        {
            User? user = GetThisUser();
            var userSkillsId = _uow.UserSkill.GetAccToFilter(userSkill => userSkill.UserId == user.UserId).Select(m => m.SkillId);
            if (user != null)
            {
                user.FirstName = obj.FirstName;
                user.LastName = obj.LastName;
                user.ProfileText = obj.ProfileText;
                user.CityId = obj.CityId;
                user.CountryId = obj.CountryId;
                user.EmployeeId = obj.EmployeeId;
                user.Department = obj.Department;
                user.Title = obj.Title;
                user.WhyIVolunteer = obj.WhyIVolunteer;
                user.LinkedInUrl = obj.LinkedInUrl;
                user.UpdatedAt = DateTime.Now;

                _uow.User.Update(user);

                if (finalSkillList.Count == 0)
                {
                    foreach (var item in userSkillsId)
                    {
                        UserSkill deleteSkill = _uow.UserSkill.GetFirstOrDefault(userSkill => userSkill.SkillId == item);
                        _uow.UserSkill.Remove(deleteSkill);
                    }
                }
                else
                {
                    var skillToBeAdded = finalSkillList.Except(userSkillsId);
                    foreach (var skillId in skillToBeAdded)
                    {
                        UserSkill uSkills = new()
                        {
                            UserId = user.UserId,
                            SkillId = skillId,
                        };
                        _uow.UserSkill.Add(uSkills);
                    }

                    var skillToBeDeleted = userSkillsId.Except(finalSkillList);
                    foreach (var skillid in skillToBeDeleted)
                    {
                        UserSkill deleteSkill = _uow.UserSkill.GetFirstOrDefault(userSkill => userSkill.SkillId == skillid);
                        _uow.UserSkill.Remove(deleteSkill);
                    }
                }
                _uow.Save();
            }

            return RedirectToAction("Profile");
        }


        //volunteering timesheet
        [Authorize]
        public IActionResult VolTimeSheet()
        {
            User? user = GetThisUser();
            IEnumerable<MissionApplication> timeBasedMissionAppList = _uow.MissionApplication.GetMissionApplicationList(mission => mission.UserId == user.UserId && mission.ApprovalStatus == "APPROVED" && mission.Mission.MissionType == "Time");
            IEnumerable<MissionApplication> TimeBasedMissionAppList = _uow.MissionApplication.GetMissionApplicationsData(user.UserId);
            IEnumerable<MissionApplication> goalBasedMissionAppList = _uow.MissionApplication.GetMissionApplicationList(mission => mission.UserId == user.UserId && mission.ApprovalStatus == "APPROVED" && mission.Mission.MissionType == "Goal");
            IEnumerable<Timesheet> timeBasedData = _uow.TimeSheet.GetTimeSheetData(timeData => timeData.UserId == user.UserId && timeData.Mission.MissionType == "Time" && timeData.DeletedAt == null);
            IEnumerable<Timesheet> goalBasedData = _uow.TimeSheet.GetTimeSheetData(goalData => goalData.UserId == user.UserId && goalData.Mission.MissionType == "Goal" && goalData.DeletedAt == null);
            VolTimeSheetViewModel obj = new();
            obj.UserDetail = user;
            obj.TimeBasedMissionAppList = timeBasedMissionAppList;
            obj.GoalBasedMissionAppList = goalBasedMissionAppList;
            obj.TimeBasedData = timeBasedData;
            obj.GoalBasedData = goalBasedData;
            return View(obj);
        }

        //add and update timesheet
        [HttpPost]
        public IActionResult AddUpdateTimesheet(VolTimeSheetViewModel obj)
        {
            User? user = GetThisUser();
            var hrs = obj.Hours;
            var min = obj.Minutes;
            TimeSpan time = new(hrs, min, 0);
            if (obj.TimeSheetId == 0)
            {
                Timesheet data = new()
                {
                    UserId = user.UserId,
                    MissionId = obj.MissionId,
                    TotalTime = time,
                    Action = obj.Action,
                    DateVolunteered = obj.DateVolunteered,
                    Notes = obj.Notes,
                    Status = "SUBMIT_FOR_APPROVAL",
                };
                _uow.TimeSheet.Add(data);

CIPlatformWeb/Views/Shared/_Footer.cshtml
<style>
    #footer {
        width: 100%;
        position: absolute;
        bottom: 0;
    }
    /*loader for sending mail*/
    #contactPageLoader {
        height: 50vh;
    }

        #contactPageLoader div {
            width: 3rem;
            height: 3rem;
            margin-top: 15%;
        }
</style>

<footer class="border-top text-muted text-center" id="footer">
    <div class="container my-4">
        &copy; 2023 - CIPlatformWeb -
        <a class="text-decoration-none text-black pe-2 fw-bold" asp-controller="Policy" asp-action="PolicyAndCookies">Privacy</a>
        @if (User.Identity.IsAuthenticated)
        {
            <span>&</span>
            <button class="border-0 bg-white mb-3" data-bs-toggle="modal" data-bs-target="#contact-us">
                <p class="mb-0 text-black fw-bold">Contact Us</p>
            </button>
            <div class="modal fade" id="contact-us" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                    <div class="modal-content">
                        <div id="model-content">
                            <form id="contactUsForm">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Contact Us</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body text-start">
                                    <div class="form-group">
                                        <label class="form-label" for="user-name">Name</label>
                                        <input type="text" class="form-control mb-2" id="user-name" value="@Model.UserDetail.FirstName @Model.UserDetail.LastName" disabled>
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label" for="user-email">Email address</label>
                                        <input type="email" class="form-control mb-2" id="user-email" aria-describedby="emailHelp" value="@Model.UserDetail.Email" disabled>
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label" for="mail-subject">Subject</label>
                                        <input type="text" class="form-control mb-2" id="mail-subject" placeholder="Example input" required>
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label" for="mail-message">Message</label>
                                        <textarea class="form-control mb-2" id="mail-message" rows="3" required></textarea>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn rounded-pill cancel-btn" data-bs-dismiss="modal">Cancel</button>
                                    <button type="button" class="btn rounded-pill send-mail-btn" onclick="sendMailToContact()">Send</button>
                                </div>
                            </form>
                        </div>
                        <div class="d-none w-100 text-center" id="contactPageLoader">
                            <div class="spinner-border text-warning" role="status">
                            </div>
                            <p>Sending Mail...</p>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</footer>

<script type="text/javascript">

    //send mail to Contact admin
    function sendMailToContact() {
        $('#contactPageLoader').removeClass('d-none');
        $('#model-content').addClass('d-none');
        var subject = $('#mail-subject').val();
        var message = $('#mail-message').val();
        if (subject != '' && message != '') {
            $.ajax({
                type: 'POST',
                url: '/Policy/ContactUsMail',
                data: { "mailSubject": subject, "mailBody": message },
                success: function (data) {
                    if (data == 1) {
                        sweetAlertAnimation("Data send successfully!");
                        $('#contactPageLoader').addClass('d-none');
                        $('#model-content').removeClass('d-none');
                        $('#contact-us').modal('toggle');
                    }
                    else {
                        sweetAlertAnimation("Opps! Something went wrong.");
                    }
                },
                error: function (e) {
                    console.log(e);
                }
            });
        }
        else {
            sweetAlertAnimation('please fill the details!');
            $('#contactPageLoader').addClass('d-none');
            $('#model-content').removeClass('d-none');
        }
    }
</script>

CIPlatformWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CIPlatformWeb</title>
    <link rel="icon" type="image/x-icon" href="/images/favicon.ico">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ciplatformweb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body>
    <div>
        <main role="main" class="pb-3">
            <partial name="_PartialViewforNavbar" />
            <partial name="_Notification" />
            @RenderBody()
            <partial name="_Footer" />
        </main>
    </div>

    @*    <script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
    *@
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/qagffr3pkuv17a8on1afax661irst1hbr4e6tbv888sz91jc/tinymce/6/tinymce.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/ShareStory.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CIPlatformWeb/Views/Shared/_LayoutForAdmin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"] - CIPlatformWeb</title>
    <link rel="icon" type="image/x-icon" href="/images/favicon.ico">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://www.tiny.cloud/css/codepen.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css">
    <link rel="stylesheet" href="~/css/sb-admin-2.css">
    <link rel="stylesheet" href="~/css//datatables.css" />
    <link rel="stylesheet" href="~/css//Admin.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" asp-append-version="true" />
    <script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body>
    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <!-- Sidebar -->
        <div class="navbar-nav sidebar sidebar-dark accordion admin-panel" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <div class="sidebar-brand d-flex align-items-center justify-content-center">
                <div class="sidebar-brand-icon">
                    <i class="bi bi-person-circle"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Admin</div>
            </div>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <div class="nav-item  disabled bg-transparent">
                <div class="nav-link disabled active bg-transparent text-white">
                    <i class="bi bi-sign-turn-slight-right-fill text-white"></i>
                    <span class="fw-bold">NAVIGATION</span>
                </div>
            </div>

            <!-- Divider -->
            <hr class="sidebar-divider">


            <!-- Nav Item - Pages Collapse Menu -->
            <ul class="navbar-nav">
                <!-- Nav Item - User -->
                <li class="nav-item list-unstyled" id="user">
                    <a class="nav-link" asp-controller="Admin" asp-action="UserDetail">
                        <i class="bi bi-person-bounding-box"></i>
                        <span>User</span>
                    </a>
                </li>

                <!-- Nav Item - CMS Page -->
                <li class="nav-item list-unstyled" id="cms">
                    <a class="nav-link" asp-controller="Admin" asp-action="CMSPage">
                        <i class="bi bi-file-earmark-fill"></i>
                        <span>CMS Page</span>
                    </a>
                </li>

                <!-- Nav Item - Mission -->
                <li class="nav-item list-unstyled" id="mission">
                    <a class="nav-link" asp-controller="Admin" asp-action="MissionDetails">
                        <i class="bi bi-bullseye"></i>
                        <span>Mission</span>
                    </a>
                </li>

                <!-- Nav Item - Mission Theme -->
                <li class="nav-item list-unstyled" id="missTheme">
                    <a class="nav-link" asp-controller="Admin" asp-action="MissionThemeDetails">
                        <i class="bi bi-columns-gap"></i>
                        <span>Mission Theme</span>
                    </a>
                </li>

                <!-- Nav Item - Mission Skills -->
                <li class="nav-item list-unstyled" id="skill">
                    <a class="nav-link" asp-controller="Admin" asp-action="SkillDetails">
                        <i class="bi bi-tools"></i>
                        <span>Skills</span>
                    </a>
                </li>

                <!-- Nav Item - Mission Application -->
                <li class="nav-item list-unstyled" id="missApp">
                    <a class="nav-link" asp-controller="Admin" asp-action="MissionApplicationDetails">
                        <i class="bi bi-folder-symlink-fill"></i>
                        <span>Mission Application</span>
                    </a>
                </li>

                <!-- Nav Item - Story -->
                <li class="nav-item list-unstyled" id="story">
                    <a class="nav-link" asp-controller="Admin" asp-action="StoryDetails">
                        <i class="bi bi-journal-album"></i>
                        <span>Story</span>
                    </a>
                </li>

                <!-- Nav Item - Banner Management -->
                <li class="nav-item list-unstyled" id="banner">
                    <a class="nav-link" asp-controller="Admin" asp-action="BannerDetails">
                        <i class="bi bi-file-earmark-image-fill"></i>
                        <span>Banner Management</span>
                    </a>
                </li>

            </ul>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle">
                </button>
            </div>

        </div>
        <!-- End of Sidebar -->
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="bi bi-list"></i>
                    </button>

                    <div class="current-time d-none d-sm-block">
                        <span>@DateTime.Now.ToString("dddd, MMMM dd, yyyy, hh:mm:ss tt")</span>
                    </div>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item dropdown">
                            <a class="nav-link" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown"
                               aria-expanded="false" style="width:auto">
                                <img src="~/images//default-user-icon.png" class="rounded-circle" height="35" width="35" alt="Profile pic"
                                     loading="lazy" id="userImg" />
                                <span class="px-2 text-black" id="userName"></span>
                                <img src="/images/drop-down.png" alt="">
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                                <li><a class="dropdown-item btn" asp-controller="User" asp-action="Profile">My Profile</a></li>
                                <li><a class="dropdown-item btn" asp-controller="Home" asp-action="Index">Landing Page</a></li>
                                <li><a class="dropdown-item btn" asp-controller="User" asp-action="Logout">Logout</a></li>
                            </ul>
                        </li>
                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <partial name="_Notification" />
                    @RenderBody()
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; CI Platform 2023</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous" asp-append-version="true"></script>
    <script src="~/js/sb-admin-2.js"></script>
    <script src="~/js/site.js"></script>
    <script type="text/javascript">
        $.ajax({
            type: 'POST',
            url: '/Common/GetThisUser',
            success: function (data) {
                $('#userImg').attr("src", data.avatar);
                $('#userName').text(data.firstName + " " + data.lastName);
            },
            error: function () {
                console.log('error');
            },
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CIPlatformWeb/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null){
    @*script for toastr*@
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.options = {
            "positionClass": "toast-bottom-right",
        }
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    @*script for toastr*@
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.options = {
            "positionClass": "toast-bottom-right",
        }
        toastr.error('@TempData["error"]');
    </script>
}