CIPlatformWeb/Controllers/StoryController.cs
using CIPlatformWeb.Entities.Data;
using CIPlatformWeb.Entities.DataModels;
using CIPlatformWeb.Entities.ViewModels;
using CIPlatformWeb.Repositories.GenericRepository.Interface;
using Grpc.Core;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Net.Mail;
using System.Net;
using System.Security.Claims;

namespace CIPlatformWeb.Controllers
{
    public class StoryController : CommonController
    {
        private readonly IUnitOfWork _uow;

        public StoryController(IUnitOfWork uow) : base(uow)
        {
            _uow = uow;
        }

        //current user details
        public User GetThisUser()
        {
            ClaimsIdentity? identity = User.Identity as ClaimsIdentity;
            string? email = identity?.FindFirst(ClaimTypes.Email)?.Value;
            User user = _uow.User.GetFirstOrDefault(m => m.Email == email);
            return user;
        }

        //Story landing page
        public IActionResult StoriesPage()
        {
            StoryPageViewModel obj = new()
            {
                UserDetail = GetThisUser(),
            };
            return View(obj);
        }

        //method for loading card data
        public IActionResult StoryCardData(int pg = 1)
        {
            User user = GetThisUser();
            IEnumerable<StoryMedium> storyMedias = _uow.StoryMedia.GetAll();
            IEnumerable<Story> stories = _uow.Story.GetAccToFilter(story => story.Status == "PUBLISHED");
            IEnumerable<MissionTheme> missionThemeList = _uow.MissionTheme.GetAll();
            IEnumerable<Mission> missList = _uow.Mission.GetAll();
            IEnumerable<User> userList = _uow.User.GetAll();
            StoryPageViewModel obj = new()
            {
                MissionThemeList = missionThemeList,
                MissionList = missList,
                UsersList = userList,
                StoryList = stories.OrderByDescending(m => m.CreatedAt),
                UserDetail = user,
                StoryMediaList = storyMedias,
            };
            int resCount = obj.StoryList.Count();
            const int pageSize = 9;
            if (pg < 1)
                pg = 1;
            PaginationViewModel pager = new PaginationViewModel(resCount, pg, pageSize);

            int recSkip = (pg - 1) * pageSize;

            obj.StoryList = obj.StoryList.Skip(recSkip).Take(pager.PageSize).ToList();

            ViewBag.storyPager = pager;

            return PartialView("_PartialViewForStoryCards", obj);
        }

        //shareyour story page
        public IActionResult ShareStory()
        {
            User user = GetThisUser();
            List<MissionApplication> draftMissAppList = new List<MissionApplication>();
            if (user != null)
            {
                IEnumerable<MissionApplication>? usersAppMission = _uow.MissionApplication.GetAccToFilter(m => m.UserId == user.UserId && m.ApprovalStatus == "APPROVED");
                foreach (var mission in usersAppMission)
                {
                    var story = _uow.Story.GetFirstOrDefault(m => m.MissionId == mission.MissionId && m.UserId == user.UserId);
                    if (story != null && (story.Status == "DRAFT" || story.Status == "DECLINED"))
                    {
                        draftMissAppList.Add(mission);
                    }
                    else if (story == null)
                    {
                        draftMissAppList.Add(mission);
                    }
                }
            }
            IEnumerable<Mission> missList = _uow.Mission.GetAll();
            IEnumerable<City> cityList = _uow.City.GetAll();
            StoryPageViewModel obj = new()
            {
                MissionList = missList,
                CityList = cityList,
                UserDetail = user,
                MissionApplicationList = draftMissAppList,
            };
            return View(obj);
        }

        [HttpPost]
        public void SaveMedia(long sId, String VideoUrls, IEnumerable<StoryMedium> storyMediaList, List<IFormFile> ImageFiles, string[] preloaded)
        {
            if (VideoUrls != null)
            {
                foreach (var video in storyMediaList)
                {
                    if (video != null && video.Type == "video")
                    {
                        _uow.StoryMedia.Remove(video);
                    }
                }
                StoryMedium strMedForVid = new()
                {
                    StoryId = sId,
                    Type = "video",
                    Path = VideoUrls,
                };
                _uow.StoryMedia.Add(strMedForVid);
            }

            //for images
            foreach (var storyMedia in storyMediaList)
            {
                if (storyMedia.Type != "video")
                {
                    if (preloaded.Length < 1)
                    {
                        string imagePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/StoryMedia/", storyMedia.Path);

                        if (System.IO.File.Exists(imagePath))
                        {
                            System.IO.File.Delete(imagePath);
                        }

                        _uow.StoryMedia.Remove(storyMedia);
                    }
                    else
                    {
                        bool flag = false;
                        for (int i = 0; i < preloaded.Length; i++)
                        {
                            string imgName = preloaded[i][12..];

                            if (imgName.Equals(storyMedia.Path))
                            {
                                flag = true;
                            }
                        }
                        if (!flag)
                        {
                            string imagePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/StoryMedia/", storyMedia.Path);

                            if (System.IO.File.Exists(imagePath))
                            {
                                System.IO.File.Delete(imagePath);
                            }

                            _uow.StoryMedia.Remove(storyMedia);
                        }
                    }
                }
            }

            if (ImageFiles?.Count > 0)
            {
                foreach (var image in ImageFiles)
                {
                    string imgExt = Path.GetExtension(image.FileName);
                    if (imgExt == ".jpg" || imgExt == ".png" || imgExt == ".jpeg")
                    {
                        string imageName = Guid.NewGuid().ToString() + Path.GetExtension(image.FileName);
                        string imgSaveTo = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/StoryMedia/" + imageName);
                        using (FileStream stream = new(imgSaveTo, FileMode.Create))
                        {
                            image.CopyTo(stream);
                        }
                        StoryMedium strMed = new()
                        {
                            StoryId = sId,
                            Type = imgExt,
                            Path = imageName,
                        };
                        _uow.StoryMedia.Add(strMed);
                    }
                }
            }

            _uow.Save();
        }

        //Save this Story
        [HttpPost]
        public IActionResult SaveThisStory(StoryPageViewModel obj, List<IFormFile> ImageFiles, string[] preloaded)
        {
            User user = GetThisUser();
            Story thisStory = _uow.Story.GetFirstOrDefault(m => m.UserId == user.UserId && m.MissionId == obj.MissionId);

            if (thisStory != null)
            {
                thisStory.Title = obj.Title;
                thisStory.Description = obj.Description;
                thisStory.MissionId = obj.MissionId;
                thisStory.UpdatedAt = DateTime.Now;
                thisStory.Status = "DRAFT";
                _uow.Story.Update(thisStory);
            }
            else
            {
                Story str = new()
                {
                    UserId = user.UserId,
                    MissionId = obj.MissionId,
                    Title = obj.Title,
                    Description = obj.Description,
                    CreatedAt = obj.DateCreated,
                    ViewCount = 0,
                };
                _uow.Story.Add(str);
                _uow.Save();
            }

            Story story = _uow.Story.GetFirstOrDefault(m => m.UserId == user.UserId && m.MissionId == obj.MissionId);
            IEnumerable<StoryMedium> storyMediaList = _uow.StoryMedia.GetAccToFilter(m => m.StoryId == story.StoryId);

            SaveMedia(story.StoryId, obj.VideoUrls, storyMediaList, ImageFiles, preloaded);

            return RedirectToAction("ShareStory");
        }

        //get drafted story data 
        public IActionResult GetDraftStoryData(int missId)
        {
            User user = GetThisUser();
            var storyDetail = new List<DraftedStoryDetails>();
            if (missId > 0)
            {
                storyDetail = _uow.Story.GetDraftedStoryDetails(missId, user.UserId);
            }

            if (storyDetail.Any())
            {
                return Json(storyDetail);
            }
            return Json(0);
        }

        //submit this story
        [HttpPost]
        public IActionResult SubmitThisStory(StoryPageViewModel obj, List<IFormFile> ImageFiles, string[] preloaded)
        {
            User? user = GetThisUser();
            Story? thisStory = new();
            if (obj != null)
            {
                thisStory = _uow.Story.GetFirstOrDefault(story => story.MissionId == obj.MissionId && story.UserId == user.UserId);
            }

            if (thisStory != null)
            {
                thisStory.Title = obj?.Title;
                thisStory.Description = obj?.Description;

CIPlatformWeb/Controllers/VolPageController.cs
using CIPlatformWeb.Entities.Data;
using CIPlatformWeb.Entities.DataModels;
using CIPlatformWeb.Entities.ViewModels;
using CIPlatformWeb.Repositories.GenericRepository.Interface;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace CIPlatformWeb.Controllers
{
    public class VolPageController : Controller
    {
        private readonly IUnitOfWork _uow;
        public VolPageController(IUnitOfWork uow)
        {
            _uow = uow;
        }

        public User GetThisUser()
        {
            ClaimsIdentity? identity = User.Identity as ClaimsIdentity;
            string? email = identity?.FindFirst(ClaimTypes.Email)?.Value;
            User? user = _uow.User.GetFirstOrDefault(m => m.Email == email);
            return user;
        }

        //Volunteering mission page 
        public IActionResult VolunteeringMissionPage(int? id)
        {
            User? user = GetThisUser();
            Mission? thisMission = _uow.Mission.GetThisMission(m => m.MissionId == id);
            IEnumerable<Mission> relatedMissions = _uow.Mission.GetMission(m => m.MissionId != id && m.DeletedAt == null && m.Status == 1 && (m.CityId == thisMission.CityId || m.CountryId == thisMission.CountryId || m.MissionThemeId == thisMission.MissionThemeId)).Take(3);
            IEnumerable<User> userList = _uow.User.GetAll();
            IEnumerable<Timesheet> achievedGoalList = _uow.TimeSheet.GetAccToFilter(timesheet => timesheet.Mission.MissionType == "Goal" && timesheet.DeletedAt == null);
            IEnumerable<GoalMission> totalGoalList = _uow.GoalMisison.GetAll();
            MissionRating UserRatingForThisMission = new MissionRating();

            if (user != null)
            {
                UserRatingForThisMission = _uow.MissionRating.GetFirstOrDefault(m => m.UserId == user.UserId && m.MissionId == id);
            }
            IEnumerable<MissionRating> missionRatingList = _uow.MissionRating.GetAll();
            IEnumerable<City> cities = _uow.City.GetAll();
            IEnumerable<Country> countries = _uow.Country.GetAll();
            IEnumerable<MissionTheme> themes = _uow.MissionTheme.GetAll();
            IEnumerable<FavoriteMission> favMissions = _uow.FavoriteMission.GetAll();
            IEnumerable<Comment> comments = _uow.Comment.GetAccToFilter(m => m.MissionId == id).OrderByDescending(m => m.CreatedAt);
            IEnumerable<MissionApplication> missAppList = _uow.MissionApplication.GetMissAppList();
            IEnumerable<MissionApplication> resVol = _uow.MissionApplication.GetAccToFilter(m => m.MissionId == id && m.ApprovalStatus == "APPROVED");

            VolunteeringPageViewModel obj = new()
            {
                UsersList = userList,
                CityList = cities,
                CountryList = countries,
                MissionThemeList = themes,
                MissionDetail = thisMission,
                UserDetail = user,
                RelatedMissionList = relatedMissions,
                FavMissionList = favMissions,
                CommentList = comments,
                UserRating = UserRatingForThisMission,
                MissionRatings = missionRatingList,
                MissionApplicationList = missAppList,
                RecentVolunteerList = resVol,
                TotalGoalList = totalGoalList,
                AchievedGoalList = achievedGoalList,
            };
            return View(obj);
        }

        //Rating by user
        public void changeRatingByUser(int rating, int missionId)
        {
            User user = GetThisUser();
            MissionRating UserRatingForThisMission = _uow.MissionRating.GetFirstOrDefault(m => m.UserId == user.UserId && m.MissionId == missionId);
            if (UserRatingForThisMission == null)
            {
                MissionRating obj = new()
                {
                    Rating = rating,
                    MissionId = missionId,
                    UserId = user.UserId,
                };
                _uow.MissionRating.Add(obj);
                _uow.Save();
            }
            else
            {
                UserRatingForThisMission.Rating = rating;
                UserRatingForThisMission.UpdatedAt = DateTime.Now;
                _uow.MissionRating.Update(UserRatingForThisMission);
                _uow.Save();
            }
        }

        //Mission application
        public void MissionApplication(int missId)
        {
            User user = GetThisUser();
            MissionApplication thisMissApp = _uow.MissionApplication.GetFirstOrDefault(m => m.UserId == user.UserId && m.MissionId == missId);
            if (thisMissApp != null && thisMissApp.ApprovalStatus == "DECLINE")
            {
                thisMissApp.ApprovalStatus = "PENDING";
                thisMissApp.AppliedAt = DateTime.Now;
                thisMissApp.UpdatedAt = DateTime.Now;
                _uow.MissionApplication.Update(thisMissApp);
                _uow.Save();
            }
            else
            {
                MissionApplication obj = new()
                {
                    UserId = user.UserId,
                    MissionId = missId,
                    AppliedAt = DateTime.Now,
                };
                _uow.MissionApplication.Add(obj);
                _uow.Save();
            }
        }

        //Add comment function 
        public IActionResult addComment(int? missId, string? commentText)
        {
            User user = GetThisUser();
            Comment obj = new()
            {
                CommentText = commentText,
                UserId = user.UserId,
                MissionId = (long)missId,
            };
            _uow.Comment.Add(obj);
            _uow.Save();

            return RedirectToAction("VolunteeringMissionPage", new { id = missId });
        }
    }
}

CIPlatformWeb/Views/Story/ShareStory.cshtml
@{
    ViewData["Title"] = "Share Story Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model StoryPageViewModel;

<link rel="stylesheet" href="https://www.tiny.cloud/css/codepen.min.css" />
<link rel="stylesheet" href="~/css/ShareStoryForm.css" />


<div class="container px-4 px-sm-2 mb-5 pb-5">
    @*heading*@
    <h1 class="my-4">Share your story</h1>

    @*story form*@
    <form enctype="multipart/form-data" method="post" id="story-form">
        <div class="row">
            <div class="col-12 col-md-4 form-group mb-4">
                <label class="mb-1" for="missionDropDownList">Select Mission</label>
                <select asp-for="MissionId" class="form-select select" id="missionDropDownList" onchange="getDraftStory()">
                    <option value="">Select Mission</option>
                    @foreach (var item in Model.MissionApplicationList)
                    {
                        <option value="@item.Mission.MissionId">@item.Mission.Title, @item.Mission.City.Name</option>
                    }
                </select>
                <span asp-validation-for="MissionId" class="text-danger"></span>
            </div>
            <div class="col-12 col-md-4 form-group mb-4">
                <label class="mb-1" for="storyTitle">My Story Title</label>
                <input asp-for="Title" type="text" class="form-control" id="storyTitle" placeholder="Enter Story Title..." maxlength="255">
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="col-12 col-md-4 form-group mb-4">
                <label class="mb-1" for="date">Date</label>
                <input asp-for="DateCreated" value="" type="date" class="form-control" id="dateCreated">
                <span asp-validation-for="DateCreated" class="text-danger"></span>
            </div>
            <div class="col-12 mb-4" id="textarea">
                <label class="mb-1" for="myStory">My Story</label>
                <textarea asp-for="Description" class="w-100" style="min-height: 300px" id="myStory"></textarea>
                <span class="text-danger d-none" id="story-desc">Required!</span>
            </div>
            <div class="col-12 mb-4">
                <label class="mb-1" for="viedoUrl">Enter Viedo URL</label>
                <input asp-for="VideoUrls" type="text" class="form-control" id="videoUrl" placeholder="Enter Youtube Viedo URL...">
                <span asp-validation-for="VideoUrls" class="text-danger"></span>
            </div>
            <div class="col-12 mb-4">
                <div class="label">
                    <p class="mb-1">Upload your Photos</p>
                </div>
                <div>
                    <label class="preview-image d-block"></label>
                </div>
            </div>

            <div class="col-12">
                <div class="row">
                    <div class="col-12 col-sm-6">
                        <a asp-controller="Story" asp-action="StoriesPage" style="width: 100px" class="btn border cancel-btn rounded-pill px-4 mb-3">Cancel</a>
                    </div>
                    <div class="col-12 col-sm-6 text-sm-end">
                        <button asp-controller="Story" asp-action="SaveThisStory" style="width: 100px" class="btn rounded-pill px-4 mb-3 me-3 save-story" id="">Save</button>
                        <button asp-controller="Story" asp-action="SubmitThisStory" style="width: 100px" class="btn rounded-pill px-4 mb-3 submit-story" disabled="disabled" id="">Submit</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<script>
    $(document).ready(function () {
        $(".preview-image").imageUploader({});
    });

    $("#story-form").on("submit", function (event) {
        let storyDesc = tinymce.activeEditor.getContent();;
        if (storyDesc == "") {
            $('#story-desc').removeClass('d-none');
            event.preventDefault();
        }
        else{
            $('#story-desc').addClass('d-none');
        }
    });
</script>

CIPlatformWeb/Views/Story/StoriesPage.cshtml
@{
    ViewData["Title"] = "Story Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model StoryPageViewModel;
@*story listing page css*@
<link rel="stylesheet" href="~/css/StoriesPage.css" asp-append-version="true" />


<!-- story posting and listing start -->
<div class="container-fluid p-0">
    <!-- story posting section start -->
    <div class="" id="shareStorySecImg">
        <div id="shareStory" class="d-flex justify-content-center flex-column my-auto mx-auto h-100">
            <p class="text-center text-white px-5">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tenetur
                similique
                iste, numquam vitae
                quo, esse modi, ipsa ad eos non corrupti id voluptatibus repudiandae! Architecto ipsa
                reprehenderit voluptatibus nobis at molestiae doloremque, ut est pariatur.
            </p>
            @if (User.Identity.IsAuthenticated)
            {
                <a asp-controller="Story" asp-action="ShareStory" class="btn d-flex align-items-center justify-content-center mx-auto my-4 px-4 py-3"
                   id="shareStoryBtn">
                    <p class="mb-0 pe-4 text-white">Share your Story</p>
                    <img src="/images/right-arrow2.png" alt="">
                </a>
            }
            else
            {
                <button class="btn d-flex align-items-center justify-content-center mx-auto my-4 px-4 py-3"
                   id="shareStoryBtn" onclick="Alert('Please Login First!')">
                    <p class="mb-0 pe-4 text-white">Share your Story</p>
                    <img src="/images/right-arrow2.png" alt="">
                </button>
            }
        </div>
    </div>
    <!-- story posting section end -->
    <div id="story-list">

    </div>
    @*<partial name="_PartialViewForStoryCards"></partial>*@
</div>
<!-- story posting and listing end -->
@*story listing javascript*@
<script>
    $(document).ready(function () {
        storyListing(1);
    });
    function storyListing(pg) {
        $.ajax({
            url: "/Story/StoryCardData",
            method: "POST",
            dataType: "html",
            data: { "pg": pg },
            success: function (data) {

                $('#story-list').html("");
                $('#story-list').html(data);
            },
            error: function (error) {
                console.log(error);
            }
        });
    }
</script>

CIPlatformWeb/Views/Story/StoryDetail.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Story Detail Page";
}

@model StoryDetailViewModel;

<link rel="stylesheet" href="~/css/StoryDetail.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/slider.css" asp-append-version="true" />

<div class="container-fluid my-3" style="padding: 0 5%">
    <div class="row">
        <div class="col-12 col-lg-6 mx-auto justify-content-center">
            @if (Model.StoryDetail.StoryMedia.Any())
            {
                <!-- Container for the image gallery -->
                <div style="height: 100%">

                    <!-- Full-width images with number text -->
                    <div class="position-relative" style="height: 400px">
                        @foreach (var media in Model.StoryDetail.StoryMedia)
                        {
                            if (media.Type != "video")
                            {
                                <div class="mySlides h-100">
                                    <img class="h-100 slider-images"
                             src="/StoryMedia/@media.Path"
                             style="width:100%;">
                                </div>
                            }
                            else
                            {
                                string videoId = media.Path.Replace("https://youtu.be/", "");
                                string videoUrl = $"https://www.youtube.com/embed/{videoId}";
                                <div class="mySlides h-100 ">
                                    <iframe class="h-100 w-100 slider-images" src="@videoUrl"></iframe>
                                </div>
                            }
                        }
                        <!-- Next and previous buttons -->
                        <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
                        <a class="next" onclick="plusSlides(1)">&#10095;</a>
                    </div>




                    <!-- Thumbnail images -->
                    <div class="row mt-2 w-100 mx-auto position-relative d-flex justify-content-center" style="height: 100px">
                        <div class="thumb-images d-flex">
                            @{
                                var current = 1;
                            }
                            @foreach (var media in Model.StoryDetail.StoryMedia)
                            {
                                if (media.Type != "video")
                                {
                                    <div class="column">
                                        <img class="demo cursor"
                                 src="/StoryMedia/@media.Path"
                                 onclick="currentSlide(@current)" alt="">
                                    </div>
                                }
                                else
                                {
                                    <div class="column">
                                        <img class="demo cursor" src="~/images//icons8-youtube-240.png" onclick="currentSlide(@current)"></img>
                                    </div>
                                }
                                current++;
                            }
                        </div>
                    </div>
                </div>
            }
            else
            {
                <img class="card-img-top" id="mission-img"
                 src="/images/no-mission-image-to-show.png"
                 alt="Card image cap">
            }
        </div>
        <div class="col-12 col-lg-6 mt-lg-0 mt-3">
            <div class="card-body p-0">
                <div>
                    <img class="thisUser mt-4" src="@Model?.UserDetailOfThisStory?.Avatar" />
                </div>
                <div class="d-flex justify-content-between align-items-center">
                    <p class="mb-0">@Model?.UserDetailOfThisStory?.FirstName @Model?.UserDetailOfThisStory?.LastName</p>
                    <div class="d-flex align-items-center justify-content-between totalViews">
                        <img class="me-2" src="~/images/eye.png" />
                        <p class="mb-0"><span class="me-1">@Model?.StoryDetail?.ViewCount</span>Views</p>
                    </div>
                </div>
                <div class="whyIVolunteer mt-4">
                    <p class="why-i-volunteer">
                        @Model?.UserDetailOfThisStory?.WhyIVolunteer
                    </p>
                </div>
                <div class="container mx-auto row mt-4 mb-3">
                    <div class="col-12 col-sm-6 mb-3">
                        @if (User.Identity.IsAuthenticated)
                        {

                            var views = Model?.StoryDetail?.ViewCount + 1;

                            <a class="d-flex align-items-center justify-content-center mx-auto text-decoration-none text-black recommen-to-co" data-bs-toggle="modal" data-bs-target="#rec-this-story">
                                <img class="me-2" src="/images/add1.png" alt="">
                                <small class="mb-0 h6">Recommend to a Co-Worker</small>
                            </a>
                            <div class="modal fade" id="rec-this-story" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                                    <div class="modal-content">
                                        <div id="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Recommend this Mission</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                            </div>
                                            <div class="modal-body">
                                                @foreach (User item in Model.UserList)
                                                {
                                                    <div class="form-check my-4 user-list">
                                                        <input class="form-check-input checkbox ms-2 me-4" type="checkbox" id="@item.UserId">
                                                        <img class="rec-user-img me-2" src="@item.Avatar" alt="">
                                                        <label class="form-check-label" for="">@item.FirstName @item.LastName</label>
                                                    </div>
                                                }
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn cancel-btn rounded-pill" data-bs-dismiss="modal">Close</button>
                                                <button type="button" class="btn send-mail-btn rounded-pill" onclick="sendStoryRec(@Model?.StoryDetail?.StoryId, @views)">Send Mail</button>
                                            </div>
                                        </div>
                                        <div class="d-none w-100 text-center" id="storyPageLoader">
                                            <div class="spinner-border text-warning" role="status">
                                            </div>
                                            <p>Sending Mail...</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                        else
                        {
                            <a class="d-flex align-items-center justify-content-center mx-auto text-decoration-none text-black recommen-to-co" onclick="Alert('Please Login First!')">
                                <img class="me-2" src="/images/add1.png" alt="">
                                <small class="mb-0 h6">Recommend to a Co-Worker</small>
                            </a>
                        }
                    </div>
                    <div class="col-12 col-sm-6 mb-3">
                        <a class="d-flex align-items-center justify-content-center mx-auto text-decoration-none open-mission" asp-controller="VolPage" asp-action="VolunteeringMissionPage" asp-route-id="@Model.StoryDetail.MissionId">
                            <small class="mb-0 h6 me-3">Open Mission</small>
                            <i class="bi bi-arrow-right"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="">
        <div class="storyTitle mt-3 border-bottom">
            <h3 class="mb-3">
                @Model.StoryDetail.Title
            </h3>
        </div>
        <div class="storyDesc mb-5">
            @Html.Raw("<div class='py-4'>" +  @Model.StoryDetail.Description + "</div>")
        </div>
    </div>
</div>

<script src="~/js/StoryDetail.js"></script>
<script src="~/js/Carousel.js"></script>